 > в чем главное различие между паттернами `событие` и `команда`?

Это один из подходов реализации событийно-управляемой архитектуры, которая позволяет нам разделить бизнес-логику и некие 'побочные следствия'

Главное различие здесь в том, что `событие` - это некое побочное следствие, вытекающее из `команды`. То-есть изначально у нас выполняется некий "приказ" в виде `команды` для системы и мы ожидаем, что он либо выполнится успешно, либо вернёт ошибку — нам важно знать, что произошло, далее выполняется бизнес-логика и только после успешного выполнения команды у нас в фоне могут выполняться какие-то события.

### 1. **Команды (Commands)** — это **инициаторы**, и **результат важен.**

- В команде мы **пытаемся изменить состояние системы**: например, создать заказ, поменять количество, добавить партию.
- Если в обработке команды случилась ошибка (например, база легла, или валидация не прошла) — **это ошибка бизнес-логики**, и мы **не должны замалчивать её!**

### 2. **События (Events)** — это **факты, на которые можно (но не обязано) реагировать.**

- Событие говорит: _«Что-то случилось»_
- Событие уже **не влияет на состояние системы**, оно **следствие** (не причина).
- Поэтому: если у тебя, скажем, не получилось отправить уведомление по `OutOfStock` — ну и **чёрт с ним**, **товара всё равно нет**, это уже свершившийся факт.


>[!info] Пример реализации

```python
if TYPE_CHECKING:  
    from src.allocation.service_layer import unit_of_work  
  
Message = commands.Command | events.Event  
  
  
def handle(message: Message, uow: "unit_of_work.AbstractUnitOfWork"):  
    results = []  
    queue = [message]  
    while queue:  
        message = queue.pop(0)  
        if isinstance(message, events.Event):  
            handle_event(message, queue, uow)  
        elif isinstance(message, commands.Command):  
            cmd_result = handle_command(message, queue, uow)  
            results.append(cmd_result)  
        else:  
            raise Exception(f"{message} was not an Event or Command")  
    return results  
  
  
def handle_event(  
    event: events.Event,  
    queue: list[Message],  
    uow: unit_of_work.AbstractUnitOfWork,  
):  
    for handler in EVENT_HANDLERS[type(event)]:  
        try:  
            for attempt in Retrying(  
                stop=stop_after_attempt(3),  
                wait=wait_exponential(),  
            ):  
                with attempt:  
                    logger.debug(  
                        "handling event %s with handler %s",  
                        event,  
                        handler,  
                    )  
                    handler(event, uow=uow)  
                    queue.extend(uow.collect_new_events())  
        except RetryError as retry_failure:  
            logger.error(  
                "Не получилось обработать событие %s раз, отказ!",  
                retry_failure.last_attempt.attempt_number,  
            )  
            continue  
  
  
def handle_command(  
    command: commands.Command,  
    queue: list[Message],  
    uow: unit_of_work.AbstractUnitOfWork,  
):  
    logger.debug("handling command %s", command)  
    try:  
        handler = COMMAND_HANDLERS[type(command)]  
        result = handler(command, uow=uow)  
        queue.extend(uow.collect_new_events())  
        return result  
    except Exception:  
        logger.exception("Error handling command %s", command)  
        raise  
  
  
EVENT_HANDLERS: dict[Type[events.Event], list[Callable]] = {  
    events.OutOfStock: [handlers.send_out_of_stock_notification],  
}  
  
COMMAND_HANDLERS: dict[Type[commands.Command], Callable] = {  
    commands.Allocate: handlers.allocate,  
    commands.CreateBatch: handlers.add_batch,  
    commands.ChangeBatchQuantity: handlers.change_batch_quantity,  
}
```
Тоесть как мы видим - в `командах` мы агрессивно реагируем на возникающие ошибки, а в `событиях` - попросту пытаемся повторить попытку (что не обязательно) и умалчиваем о ошибках, разве что логируем это для дальнейшего (условно) дебага

> [!summary] TL;DR
> - Команды = инициаторы, важен результат, ошибки нельзя игнорировать
> - События = факты, важна реакция, ошибки допустимы и не критичны

[[macbook/Родительские классы/IT/Архитектура/Архитектура|Архитектура]] [[IT]]